---
title: "Yaml_integration_explore"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Yaml_integration_explore}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(megametadata)
library(yaml)
library(dplyr)
```


```{r}


here::here("template.yml") %>%
        read_yaml() -> tester

tester$AccountLevel <- iris %>% metaVariableAppend(tester$AccountLevel)

here::here("dict_spec.yml") %>%
        read_yaml() -> spec



write_yaml(tester, here::here("dict.yml") )

#tester <- list()

test_data <- iris %>% as_tibble()

#appendIntegerMeta <- function(a_dataframe, a_list, a_column){
 #       if(is.null(a_list[[a_column]])) {
  #              a_list[[a_column]] <- list()
   #     }
#
 #       a_list[[a_column]][["min"]] <- min(a_dataframe[[a_column]])
  #      a_list[[a_column]][["max"]] <- max(a_dataframe[[a_column]])
   #     a_list[[a_column]][["name"]] <- a_column
    #    a_list
#}

#test_list <- test_data %>%
 #       appendIntegerMeta(tester, "Sepal.Length")



test_data[["Sepal.Length"]]

tester[["AccountLevel"]][["Sepal.Length"]][["class"]]

spec[["AccountLevel"]][["numeric"]]

for(i in colnames(iris)){
  

tester[["AccountLevel"]][[i]]  <- tester[["AccountLevel"]][[i]] %>%  append(
  spec[["AccountLevel"]][[
    tester[["AccountLevel"]][[i]][["class"]]
    ]] %>%
    map(utilEvalOnData, test_data[[i]])
)
}
  
  


```

